version: '3'

services:
  rest-api:
    build:
      context: .
    depends_on:
      - postgresql
    environment:
      - DB_HOST=postgresql
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=movies
    ports:
      - "3000:3000"
  postgresql:
    image: postgres:9.5-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=movies
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"