version: '3'

services:
  rest-api:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
    depends_on:
      - postgresql
    environment:
      - DB_HOST=postgresql
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=movies
    ports:
      - "3000:3000"